# class                         border    backgr.    text     indicator
# client.focused              #333333   #2f2f2f   #f1f1f1   #d64937
# client.unfocused            #1b1b1b   #2a2a2a   #999999
# client.focused_inactive     #1b1b1b   #444444   #aaaaaa
# client.urgent               #d64937   #444444   #000000   #d64937

set $color-primary #ff9900
set $color-secondary #000000
set $color-tertiary #204a87
set $color-alert #bd2c40
set $color-light-gray #acacac
set $color-medium-gray #777777
set $color-dark-gray #555555
set $color-black #000000
set $color-white #e6e6e6

# state                    border              background          text                 indicator
client.focused             $color-dark-gray    #ff0074             $color-white         $color-medium-gray
client.focused_inactive    $color-black        $color-black        $color-medium-gray   $color-black
client.unfocused           $color-black        $color-black        $color-dark-gray     $color-black
client.urgent              $color-alert        $color-alert        $color-black         $color-black
client.placeholder         $color-black        $color-black        $color-white         $color-black
client.background          $color-black

