# resize window
mode "resize" {
  bindsym h resize shrink width 10 px or 10 ppt
  bindsym k resize grow height 10 px or 10 ppt
  bindsym j resize shrink height 10 px or 10 ppt
  bindsym l resize grow width 10 px or 10 ppt

  bindsym Return mode "default"
  bindsym Escape mode "default"
  bindsym $mod+r mode "default"
}
bindsym $mod+r mode "resize"

set $mode_launcher Launch: [f]irefox [t]hunderbird [c]hrome [d]iscord [s]lack [v]lc
mode "$mode_launcher" {
    bindsym f exec --no-startup-id firefox
    bindsym t exec --no-startup-id thunderbird
    bindsym c exec --no-startup-id chromium
    bindsym d exec --no-startup-id discord
    bindsym s exec --no-startup-id slack
    bindsym v exec --no-startup-id vlc

    bindsym Escape mode "default"
    bindsym Return mode "default"
}
bindsym $mod+o mode "$mode_launcher"

set $Locker i3lock && sleep 1
set $mode_power [l]lock [e]logout [s]suspend [h]hibernate [r]reboot [S]shutdown
mode "$mode_power" {
    bindsym l exec --no-startup-id i3lock -c 009999 && sleep 300 && systemctl suspend, mode "default"
	bindsym e exec --no-startup-id i3-msg exit, mode "default"
	bindsym s exec --no-startup-id $Locker && systemctl suspend, mode "default"
	bindsym h exec --no-startup-id $Locker && systemctl hibernate, mode "default"
	bindsym r exec --no-startup-id systemctl reboot, mode "default"
	bindsym Shift+s exec --no-startup-id systemctl poweroff -i, mode "default"

    bindsym Escape mode "default"
    bindsym Return mode "default"
}
bindsym $mod+Escape mode "$mode_power"

set $mode_filemarks [1]stat107 [2]cs233 [3]hdfs220 [4]repos [5]configs [6]scripts
mode "$mode_filemarks" {
    bindsym 1 exec --no-startup-id alacritty -e /bin/bash -c "cd /home/aarya/GoogleDrive/uiuc/senior/spring/STAT107 && /bin/bash", mode "default"
    bindsym 2 exec --no-startup-id alacritty -e /bin/bash -c "cd /home/aarya/GoogleDrive/uiuc/senior/spring/CS233 && /bin/bash", mode "default"
    bindsym 3 exec --no-startup-id alacritty -e /bin/bash -c "cd /home/aarya/GoogleDrive/uiuc/senior/spring/CS233 && /bin/bash", mode "default"
    bindsym 4 exec --no-startup-id alacritty -e /bin/bash -c "cd /home/aarya/repos && /bin/bash", mode "default"
    bindsym 5 exec --no-startup-id alacritty -e /bin/bash -c "cd /home/aarya/.config && /bin/bash", mode "default"
    bindsym 6 exec --no-startup-id alacritty -e /bin/bash -c "cd /home/aarya/scripts && /bin/bash", mode "default"

    bindsym Escape mode "default"
    bindsym Return mode "default"
}
bindsym $mod+m mode "$mode_filemarks"

set $mode_gaps Gaps: (o) outer, (i) inner
set $mode_gaps_outer Outer Gaps: +|-|0 (local), Shift + +|-|0 (global)
set $mode_gaps_inner Inner Gaps: +|-|0 (local), Shift + +|-|0 (global)
bindsym $mod+Shift+g mode "$mode_gaps"

mode "$mode_gaps" {
        bindsym o      mode "$mode_gaps_outer"
        bindsym i      mode "$mode_gaps_inner"
        bindsym Return mode "default"
        bindsym Escape mode "default"
}

mode "$mode_gaps_inner" {
        bindsym plus  gaps inner current plus 5
        bindsym minus gaps inner current minus 5
        bindsym 0     gaps inner current set 0

        bindsym Shift+plus  gaps inner all plus 5
        bindsym Shift+minus gaps inner all minus 5
        bindsym Shift+0     gaps inner all set 0

        bindsym Return mode "default"
        bindsym Escape mode "default"
}
mode "$mode_gaps_outer" {
        bindsym plus  gaps outer current plus 5
        bindsym minus gaps outer current minus 5
        bindsym 0     gaps outer current set 0

        bindsym Shift+plus  gaps outer all plus 5
        bindsym Shift+minus gaps outer all minus 5
        bindsym Shift+0     gaps outer all set 0

        bindsym Return mode "default"
        bindsym Escape mode "default"
}
