[Gmail]
source           = notmuch://~/.mail
outgoing         = msmtp-enqueue.sh --read-envelope-from
default          = Primary
from             = "Aarya Bhatia" <aarya.bhatia1678@gmail.com>
query-map        = ~/.config/aerc/Gmail.qmap
check-mail-cmd   = echo AERC_SYNC >> /tmp/mail_signal.fifo
folders          = Primary, Secondary, Archive, Trash, Important, Sent
address-book-cmd = abook --mutt-query '%s'
maildir-store    = ~/.mail/

[Server]
source           = maildir://~/.mail/aaryab.in/
outgoing         = msmtp-enqueue.sh --read-envelope-from
default          = INBOX
from             = "Aarya Bhatia" <aarya@aaryab.in>
check-mail-cmd   = echo AERC_SYNC >> /tmp/mail_signal.fifo
