[Gmail]
source             = notmuch://~/Mail
outgoing           = msmtp-enqueue.sh --read-envelope-from
default            = INBOX
from               = "Aarya Bhatia" <aarya.bhatia1678@gmail.com>
query-map          = ~/.config/aerc/Gmail.qmap
check-mail-cmd     = mbsync -q -a && msmtp-runqueue.sh && notmuch new
check-mail         = 2m
check-mail-timeout = 60s

# folders-exclude    = [Gmail]
# maildir-store      = ~/Mail/
