[Gmail]
source             = notmuch://~/Mail
outgoing           = msmtp-enqueue.sh --read-envelope-from
default            = INBOX
from               = "Aarya Bhatia" <aarya.bhatia1678@gmail.com>
query-map          = ~/.config/aerc/Gmail.qmap
check-mail-cmd     = echo AERC_SYNC >> /tmp/mail_signal.fifo
maildir-store      = ~/Mail/
# folders            = INBOX, Archive, gmail/INBOX,gmail/[Gmail]/All Mail,gmail/[Gmail]/Sent Mail,aaryabhatia6/INBOX,aaryabhatia6/[Gmail]/All Mail,aaryabhatia6/[Gmail]/Sent Mail
folders           = INBOX, Archive, Trash, Sent, Spam
address-book-cmd   = abook --mutt-query '%s'

# signature-file     =  ~/.config/aerc/signatures/signature
# archive            = ~/Mail/Archive

