which bat &>/dev/null && alias cat="bat --plain"
which trash-put &>/dev/null && alias rm="trash-put"

alias ...="cd ../.."
alias ..="cd .."

alias bc="bc -q"
alias bright="brightnessctl"
alias cd="cd -P"
alias cp="cp -vi"
alias df="df -hT"
alias diff="diff --color=auto"
alias dmesg="dmesg --color=auto"
alias dot="/usr/bin/git --git-dir=$HOME/git/dotfiles/ --work-tree=$HOME"
alias du="du -h"
alias ff=fastfetch
alias free="free -h"
alias g="git"
alias grep="grep --color=auto"
alias egrep="grep -E --color=auto"
alias fgrep="grep -F --color=auto"
alias ip="ip --color=auto"
alias iv="nsxiv"
alias j="sudo journalctl"
alias keychain="keychain --dir /run/user/$UID --absolute"
alias la="ls --color=auto -Ah"
alias ll="ls --color=auto -alFh"
alias l="ls --color=auto -CF"
alias l.="ls -d .*"
alias ls="ls --color=auto --group-directories-first"
alias memcheck="valgrind --leak-check=full --show-leak-kinds=all"
alias mkdir="mkdir -pv"
alias mutt="neomutt"
alias mv="mv -i"
alias open="mimeopen"
alias paclean="sudo pacman -Rsn \$(pacman -Qdtq)"
alias please="sudo "
alias p="sudo pacman"
alias pwd="pwd -P"
alias py="python3"
alias rclone="rclone -P"
alias s="sudo systemctl"
alias sudo="sudo "
alias ta="tmux a"
alias todo="todo.sh"
alias tree="tree -C --gitignore"
alias t=tmux
alias vbox="VBoxManage"
alias vim="nvim"
alias v="nvim"
alias xopen="xdg-open"
alias xsel="xsel -b"
alias y="yay"
alias z="zathura"

alias todos='pter ~/.todo/todo.txt'
alias trayer='trayer --edge top --align center --width 6'
alias showkey="xev | awk -F'[ )]+' '/^KeyPress/ { a[NR+2] } NR in a { printf \"%-3s %s\n\", \$5, \$8 }'"
