# -------------------------------------------------
# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'nhdaly/tmux-better-mouse-mode'
set -g @plugin 'seebi/tmux-colors-solarized'
set -g @plugin 'sainnhe/tmux-fzf'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @resurrect-strategy-nvim 'session'
set -g @plugin 'tmux-plugins/tmux-continuum'

# -------------------------------------------------

# set-option -g default-shell /usr/bin/bash
# set -ga terminal-overrides ",xterm-256color*:Tc"

set -g default-terminal "screen-256color"

set -g history-limit 100000
set -g mouse on
set -s set-clipboard on

bind-key b command-prompt -p "join pane from:"  "join-pane -s '%%'"

# Change prefix and clear C-b
unbind-key C-b
set-option -g prefix C-a
bind-key C-a send-prefix

# set base index for windows and panes
set -g base-index 1
setw -g pane-base-index 1

# Hot reload
bind r source-file ~/.tmux.conf \; display "Reloaded config file."

setw -g mode-keys vi
set -g status-keys vi

# set -g status-left-length 30

# begin copy mode with vi keys (v) in addition to [
bind -T copy-mode-vi v send -X begin-selection

bind -r C-l resize-window -A \; display "Resized window."

# Navigate panes with prefix + hjkl
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# Resizing panes with prefix + HJKL
bind -r H resize-pane -L 2
bind -r J resize-pane -D 2
bind -r K resize-pane -U 2
bind -r L resize-pane -R 2

# Make new panes open in current directory
bind c new-window -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"
bind '"' split-window -v -c "#{pane_current_path}"

run-shell ~/.tmux/plugins/tmux-continuum/continuum.tmux

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
