#!/bin/sh
# feh --no-fehbg --bg-scale '/home/aarya/wallpapers/0001.jpg'
# feh --no-fehbg --bg-scale '/home/aarya/wallpapers/0048.jpg'
# feh --no-fehbg --bg-scale '/home/aarya/wallpapers/0003.jpg'
feh --no-fehbg --bg-scale '/home/aarya/wallpapers/0280.jpg'
