set -g mouse off

# set -g default-terminal "xterm-256color"
set-option -g default-terminal "screen-256color"

# Change prefix to C-a and clear C-b
unbind-key C-b
set-option -g prefix C-a
bind-key C-a send-prefix

# set delay between prefix and command
set -s escape-time 1

# set base index for windows and panes
set -g base-index 1
setw -g pane-base-index 1

# Hot reload
bind r source-file ~/.tmux.conf \; display "Reloaded config file."

setw -g mode-keys vi
set -g status-keys vi

set-option -g history-limit 100000

bind-key -Tcopy-mode-vi v send-keys -X begin-selection
bind-key -Tcopy-mode-vi y send-keys -X copy-selection

bind C-c run "tmux save-buffer - | xsel -i -b"
bind C-v run  "tmux set-buffer  \"$( xsel -o -b ) \" ; tmux paste-buffer"

bind -r C-l resize-window -A \; display "Resized window."

# Navigate panes with hjkl
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# Navigate windows
bind -r C-j select-window -p
bind -r C-k select-window -n

# Resizing panes
bind -r H resize-pane -L 2
bind -r J resize-pane -D 2
bind -r K resize-pane -U 2
bind -r L resize-pane -R 2

# Make new panes open in current directory
bind c new-window -c "#{pane_current_path}"
bind '"' split-window -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"

# set the status line colors
set -g status-style fg=white,bg=black

# set the color of window list
set -g window-status-style fg=cyan,bg=black
set -g window-status-current-style fg=white,bold,bg=red

# active pane normal, other shaded out
# setw -g window-style fg=colour240,bg=colour235
# setw -g window-active-style fg=white,bg=black

# Command/message line
set -g message-style fg=white,bold,bg=black

# Hide the status on right side
set-option -g status-right ""


# Status Bar
# set -g status-bg "#343F44"
# set -g status-fg white
#
# set -g status-position bottom
# set -g status-justify left
# set -g status-style 'bg=colour18 fg=white'
# set -g status-left ''
# set -g status-right '#[fg=#3D484D,bg=#343F44]#[fg=white,bg=#3D484D] %d/%m #[fg=#83C092,bg=#3D484D]#[fg=#2D353B,bg=#83C092] %H:%M:%S '
# set -g status-right-length 50
# set -g status-left-length 20
#
# setw -g window-status-current-style 'fg=#3D484D bg=#A7C080 bold'
# setw -g window-status-current-format ' #I#[fg=#475258]:#[fg=#3D484D]#W#[fg=#56635f]#F #[fg=#A7C080,bg=#343F44]'
#
# setw -g window-status-style 'fg=white bg=#475258'
# setw -g window-status-format ' #I#[fg=white]:#[fg=white]#W#[fg=white]#F '
