title    Arch Linux
linux    /vmlinuz-linux
initrd   /intel-ucode.img
initrd   /initramfs-linux.img
options  root=UUID=705e7f80-03b4-4d42-a396-e63d60895f5b rw quiet splash mem_sleep_default=deep resume=UUID=c43c0c99-0448-4ee4-ab5f-8afc12dd6313

