source $VIM_DIR/main.vim
source $VIM_DIR/keymaps.vim
source $VIM_DIR/autocmds.vim
source $VIM_DIR/abbrev.vim

" Vim Plug {{{

call plug#begin("$HOME/.vim/plugged")

Plug 'tpope/vim-sensible'		" sensible defaults
Plug 'sheerun/vim-polyglot' 	" syntax highlighting
Plug 'tpope/vim-commentary' 	" comments
Plug 'tpope/vim-surround'		" surround operator
Plug 'tpope/vim-repeat'
Plug 'tpope/vim-fugitive'		" git tool
Plug 'jamessan/vim-gnupg'       " edit gpg files in vim
Plug 'kana/vim-textobj-user'
Plug 'andymass/vim-matchup'
Plug 'wellle/targets.vim'		" text objects

source $VIM_DIR/plugins/fzf.vim
source $VIM_DIR/plugins/status.vim
source $VIM_DIR/plugins/ack.vim
source $VIM_DIR/plugins/tagbar.vim
source $VIM_DIR/plugins/theme.vim

call plug#end()

" }}}

colorscheme gruvbox-material

let g:netrw_liststyle = 3
