# Change prefix to C-a
unbind-key C-b
set-option -g prefix C-a
bind-key C-a send-prefix

# Navigate panes hjkl
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

setw -g mode-keys vi
set -g status-keys vi
set -g status-style fg=colour136,bg=#002b36
set -g mouse off
set -g set-clipboard on
set -g default-terminal "xterm-256color"

# Make new panes open in current directory
bind c new-window -c "#{pane_current_path}"
bind '"' split-window -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"

# Hide right side status
set-option -g status-right ""

# Set a larger scroll back
set-option -g history-limit 100000

# quiter setup
set -g visual-activity off
set -g visual-bell off
set -g visual-silence off
setw -g monitor-activity off
set -g bell-action none

# plugins 
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
run '~/.tmux/plugins/tpm/tpm'

