# Change prefix to C-a
unbind-key C-b
set-option -g prefix C-a
bind-key C-a send-prefix

set -g mouse off
setw -g mode-keys vi
set -g status-keys vi
set -g default-terminal "xterm-256color"
set-option -g history-limit 100000

# hot reload
bind r source-file ~/.tmux.conf

# Navigate panes hjkl
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# Make new panes open in current directory
bind c new-window -c "#{pane_current_path}"
bind '"' split-window -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"

set status-position top

# plugins 

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'

set -g @plugin 'catppuccin/tmux'
set -g @catppuccin_flavour 'frappe' # or latte, frappe, macchiato, mocha
set -g @catppuccin_window_tabs_enabled on

set status-right "#[fg=white] #(uname) #[default]"

run '~/.tmux/plugins/tpm/tpm'

