#! /bin/sh

primary=eDP-1
secondary=HDMI-1

## autostart
if [ $1 -eq 0 ]; then
	dunst &
	lxsession &
	mpd &
	nm-applet &
	picom --backend glx --xrender-sync-fence &
	sxhkd &
fi

numlock on
~/scripts/wallpaper.sh /home/aarya/wallpapers/archlinux/sunset.jpg
~/.config/lemonbar/launchlemon.sh 2>/tmp/lemonbar.err &
~/scripts/keymaps.sh
~/scripts/screenmirror.sh

# ~/.config/polybar/launch.sh &

bspc monitor $primary -d 1 2 3 4 5 6 7 8 9

bspc config border_width         2
bspc config window_gap          10

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
