#!/bin/sh

primary=eDP-1
secondary=HDMI-1

## autostart

xsetroot -cursor_name left_ptr & # set cursor style
numlockx on # turn on numlock
~/.config/polybar/bspwm_launch.sh & # launch top polybar
~/.config/lemonbar/launchlemon.sh & # launch bottom lemonbar
~/scripts/keymaps.sh & # setup keyboard mappings
~/scripts/wallpaper.py & # set wallpaper to last used

# start notification daemon
pgrep -f dunst || dunst &

# start session manager
pgrep -f lxsession || lxsession &

# start music player daemon
pgrep -f mpd || mpd &

pgrep -f picom || picom --backend glx --xrender-sync-fence & # start compositor

# start simple X hotkey daemon
pgrep -f sxhkd || sxhkd &

# start nightlight with location services
pgrep -f redshift || ~/scripts/nightlight.sh auto &

# start screen locker
pgrep -f xss-lock || xss-lock --transfer-sleep-lock -- i3lock --nofork --ignore-empty-password --no-unlock-indicator --color=505050 &
# pgrep -f xss-lock || xss-lock --transfer-sleep-lock -- slock &

# power management
pgrep -f xfce4-power-manager || xfce4-power-manager --daemon &

# set volume
pamixer --set-volume 32 &

# set brightness
# brightnessctl set 50% &

ToggleLemonbar() {
	if pgrep -f "bspc subscribe node_state"; then
		return 0
	fi

	bspc subscribe node_state |
		while read line; do
			action=$(echo $line | awk '{print $5}')

			if [ $action = "fullscreen" ]; then
				value=$(echo $line | awk '{print $6}')
				if [ $value = "on" ]; then
					ID=$(xdo id -N "Bar")
					[ -z "$ID" ] || xdo hide "$ID"
				else
					ID=$(xdo id -N "Bar")
					[ -z "$ID" ] || xdo show "$ID"
				fi
			fi
		done
}

ToggleLemonbar &

Multiscreen() {
	bspc monitor $primary -d 1 2 3 4 5
	bspc monitor $secondary -d 6 7 8 9 10
	xrandr | grep -q "HDMI-1 connected" && /home/aarya/.screenlayout/horizontal.sh &
}

Mirror() {
	# bspc monitor $primary -d 1 2 3 4 5 6 7 8 9 10
	bspc monitor $primary -d I II III IV V VI VII VIII IX X
	/home/aarya/scripts/screenmirror.sh &
}

Mirror

bspc config border_width        2
bspc config window_gap          8

bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config normal_border_color             "#4c566a"
bspc config focused_border_color            "#5e81ac"
bspc config presel_border_color             "#5e81ac"

# use super+mouse to drag/resize floating windows
bspc config pointer_modifier mod1
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action2 resize_corner

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a zoom state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a Thunar state=floating center=true rectange=960x750++
bspc rule -a floating center=true state=floating
bspc rule -a qalc state=floating center=true rectangle=520x400
