#!/bin/sh

primary=eDP-1
secondary=HDMI-1

# autostart
source ~/.config/bspwm/autostart.sh >> $HOME/.bspwm.autostart.log

# monitors
bspc monitor $primary -d main www mail media sys doc etc games tmp

# settings
bspc config border_width        1
bspc config window_gap          0
bspc config top_padding         24
bspc config bottom_padding       0
bspc config click_to_focus      true
bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true
bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config merge_overlapping_monitors true

# use super+mouse to drag/resize floating windows
bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action2 resize_corner

# rules
bspc rule -r "*"
bspc rule -a firefox desktop=^2 follow=on
bspc rule -a thunderbird desktop=^3 follow=on
bspc rule -a zoom desktop=^3 follow=on
bspc rule -a Ario desktop=^4 follow=on
bspc rule -a email desktop=^3 follow=on

bspc rule -a Nsxiv state=floating
bspc rule -a mplayer2 state=floating
bspc rule -a QtSpim state=floating
bspc rule -a mpv state=floating
bspc rule -a Screenkey manage=off
bspc rule -a Thunar state=floating center=true rectange=520x400++
bspc rule -a floating state=floating center=true rectangle=520x400++
bspc rule -a Xfce4-appfinder state=floating center=true rectangle=520x400++

bspc config external_rules_command ~/.config/bspwm/external_rules

# colors
bspc config active_border_color     "#1e1e1e"
bspc config normal_border_color     "#4c566a"
bspc config focused_border_color    "#2196f3"
bspc config presel_feedback_color   "#5e81ac"
bspc config urgent_border_color     "#dd2727"
