#!/bin/sh

wid=$1
class=$2
instance=$3
consequences=$4

if echo $class | grep -q "^libreoffice"; then
    echo desktop=6
fi

# echo $wid $class $instance $consequences >> /tmp/bspwm_external_rules.log

# vim: ft=sh
