#!/bin/sh

Get() {
	if command -v brightnessctl > /dev/null 2>&1; then
		b=$(qalc -t $(brightnessctl get)/$(brightnessctl max)*100)
		printf "%.0f%%\n" $b
	else
		echo 0
	fi
}

echo %{u#4caf50}%{+u}Light:$(Get)%{-u}
