workspace 1 output $primary
workspace 2 output $primary
workspace 3 output $primary
workspace 4 output $primary
workspace 5 output $primary
workspace 6 output $primary
workspace 7 output $primary
workspace 8 output $primary
workspace 9 output $primary
workspace 10 output $primary

workspace 11 output $secondary
workspace 12 output $secondary
workspace 13 output $secondary
workspace 14 output $secondary
workspace 15 output $secondary
workspace 16 output $secondary
workspace 17 output $secondary
workspace 18 output $secondary
workspace 19 output $secondary
workspace 20 output $secondary

# switch to workspace
bindsym $mod+1 workspace number $ws1
bindsym $mod+2 workspace number $ws2
bindsym $mod+3 workspace number $ws3
bindsym $mod+4 workspace number $ws4
bindsym $mod+5 workspace number $ws5
bindsym $mod+6 workspace number $ws6
bindsym $mod+7 workspace number $ws7
bindsym $mod+8 workspace number $ws8
bindsym $mod+9 workspace number $ws9
bindsym $mod+0 workspace number $ws10

bindsym $mod4+1 workspace number $ws11
bindsym $mod4+2 workspace number $ws12
bindsym $mod4+3 workspace number $ws13
bindsym $mod4+4 workspace number $ws14
bindsym $mod4+5 workspace number $ws15
bindsym $mod4+6 workspace number $ws16
bindsym $mod4+7 workspace number $ws17
bindsym $mod4+8 workspace number $ws18
bindsym $mod4+9 workspace number $ws19
bindsym $mod4+0 workspace number $ws20

# move focused container to workspace
bindsym $mod+Shift+1 move container to workspace number $ws1
bindsym $mod+Shift+2 move container to workspace number $ws2
bindsym $mod+Shift+3 move container to workspace number $ws3
bindsym $mod+Shift+4 move container to workspace number $ws4
bindsym $mod+Shift+5 move container to workspace number $ws5
bindsym $mod+Shift+6 move container to workspace number $ws6
bindsym $mod+Shift+7 move container to workspace number $ws7
bindsym $mod+Shift+8 move container to workspace number $ws8
bindsym $mod+Shift+9 move container to workspace number $ws9
bindsym $mod+Shift+0 move container to workspace number $ws10

bindsym $mod4+Shift+1 move container to workspace number $ws11
bindsym $mod4+Shift+2 move container to workspace number $ws12
bindsym $mod4+Shift+3 move container to workspace number $ws13
bindsym $mod4+Shift+4 move container to workspace number $ws14
bindsym $mod4+Shift+5 move container to workspace number $ws15
bindsym $mod4+Shift+6 move container to workspace number $ws16
bindsym $mod4+Shift+7 move container to workspace number $ws17
bindsym $mod4+Shift+8 move container to workspace number $ws18
bindsym $mod4+Shift+9 move container to workspace number $ws19
bindsym $mod4+Shift+0 move container to workspace number $ws20

