[font]
size = 6.5

[font.bold]
family = "hack"
style = "Bold"

[font.bold_italic]
family = "hack"
style = "Bold Italic"

[font.italic]
family = "hack"
style = "Italic"

[font.normal]
family = "hack"
style = "Regular"

[selection]
save_to_clipboard = true

[scrolling]
history = 50000

[window]
opacity = 1.0
