[module/my_test]
type        = custom/script
interval    = 5
exec        = echo world
label       = %{F#f00}hello%{F-}: %output%

[module/my_bspwm]
type        = custom/script
tail        = true
exec        = bspwm_workspaces.py

[module/my_memory]
type        = custom/script
exec        = sb-memory
interval    = 5
label       = %{F#a7a5a5}Mem%{F-}:%output%

[module/my_date]
type        = custom/script
exec        = sb-date
interval    = 5
label       = %{F#a7a5a5}Clk%{F-}:%output%

[module/my_battery]
type        = custom/script
exec        = sb-battery
interval    = 5
label       = %{F#a7a5a5}Bat%{F-}:%output%

[module/my_disk]
type        = custom/script
exec        = sb-disk
interval    = 5
label       = %{F#a7a5a5}Used%{F-}:%output%

[module/my_weather]
type        = custom/script
exec        = sb-weather 2>/dev/null
interval    = 20
label       = %{F#a7a5a5}Temp%{F-}:%output%

[module/my_wifi]
type        = custom/script
exec        = sb-wifi
interval    = 20
label       = %{F#a7a5a5}Net%{F-}:%output%

[module/my_volume]
type        = custom/ipc
format      = <label>
hook-0      = sb-volume
initial     = 1
click-left  = volume.sh mute
click-right = pavucontrol
label       = %{F#a7a5a5}Vol%{F-}:%output%

; [module/my_brightness]
; type        = custom/ipc
; format		= <label>
; hook-0      = sb-brightness
; initial		= 1

; [module/my_dunst]
; type        = custom/ipc
; hook-0      = /home/aarya/scripts/lemonbar/dunst.sh
; hook-1      = /home/aarya/scripts/lemonbar/dunst.sh --click
; initial     = 1
; format      = <label>
; format-1    = <label>
; click-left  = "#my_dunst.hook.1"

; [module/my_uptime]
; type        = custom/script
; exec        = /home/aarya/scripts/lemonbar/uptime.sh
; interval    = 5

; [module/my_window_count]
; type        = custom/script
; tail        = true
; exec        = /home/aarya/scripts/lemonbar/window_count.sh

; [module/my_cpu]
; type        = custom/script
; interval	= 5
; exec        = sb-cpu

; [module/my_kernel]
; type        = custom/script
; exec        = /home/aarya/scripts/lemonbar/kernel.sh

; [module/my_packages]
; type        = custom/script
; exec        = /home/aarya/scripts/lemonbar/packages.sh
; interval    = 300

