[module/xwindow]
type                = internal/xwindow
label               = %title:0:60:...%

[network-base]
type                = internal/network
interval            = 5
format-connected    = <label-connected>
format-disconnected = <label-disconnected>
label-disconnected  = %{F#F0C674}%ifname%%{F#707880} disconnected

[module/wlan]
inherit             = network-base
interface-type      = wireless
label-connected     = %{F#F0C674}%ifname%%{F-} %essid% %local_ip%

[module/eth]
inherit             = network-base
interface-type      = wired
label-connected     = %{F#F0C674}%ifname%%{F-} %local_ip%

[module/my_bspwm]
type        = custom/script
tail        = true
exec        = bspwm_workspaces.py

[module/my_memory]
type        = custom/script
exec        = sb-memory
interval    = 5
label       = %{F#ffcb32}Mem %{F-}%output%

[module/my_date]
type        = custom/script
exec        = sb-date
interval    = 5
label       = %{F#ffcb32}Clk %{F-}%output%

[module/my_battery]
type        = custom/script
exec        = sb-battery
interval    = 5
label       = %{F#ffcb32}Bat %{F-}%output%

[module/my_disk]
type        = custom/script
exec        = sb-disk
interval    = 5
label       = %{F#ffcb32}Used %{F-}%output%

[module/my_weather]
type        = custom/script
exec        = sb-weather 2>/dev/null
interval    = 20
label       = %{F#ffcb32}Temp %{F-}%output%

[module/my_wifi]
type        = custom/script
exec        = sb-wifi
interval    = 20
label       = %{F#ffcb32}Net %{F-}%output%

[module/my_volume]
type        = custom/ipc
format      = <label>
hook-0      = sb-volume
initial     = 1
click-left  = volume.sh mute
click-right = pavucontrol
label       = %{F#ffcb32}Vol %{F-}%output%

[module/my_window_count]
type        = custom/script
tail        = true
exec        = ~/scripts/lemonbar/window_count.sh

[module/my_mpd]
type        = custom/script
interval    = 5
exec        = mpc current | head -c 100

; [module/my_brightness]
; type        = custom/ipc
; format		= <label>
; hook-0      = sb-brightness
; initial		= 1

; [module/my_dunst]
; type        = custom/ipc
; hook-0      = /home/aarya/scripts/lemonbar/dunst.sh
; hook-1      = /home/aarya/scripts/lemonbar/dunst.sh --click
; initial     = 1
; format      = <label>
; format-1    = <label>
; click-left  = "#my_dunst.hook.1"

; [module/my_uptime]
; type        = custom/script
; exec        = /home/aarya/scripts/lemonbar/uptime.sh
; interval    = 5

; [module/my_cpu]
; type        = custom/script
; interval	= 5
; exec        = sb-cpu

; [module/my_kernel]
; type        = custom/script
; exec        = /home/aarya/scripts/lemonbar/kernel.sh

; [module/my_packages]
; type        = custom/script
; exec        = /home/aarya/scripts/lemonbar/packages.sh
; interval    = 300

